name: Update

# Controls when the action will run.
on:
  workflow_dispatch:
  schedule:
    # Runs every 3 days
    - cron: '0 0 */7 * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run all Python scripts
      run: |
        for file in *.py; do
          echo "Running $file"
          python "$file"
        done

    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.TOKEN }}
